#!/bin/bash
#
# Generated by NeMo Run
# Run with: sbatch --requeue --parsable
#

# Parameters
#SBATCH --account=coreai_mlperf_training
#SBATCH --exclusive
#SBATCH --job-name=coreai_mlperf_training-training.deepseek_v3_conversion
#SBATCH --mem=0
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=1
#SBATCH --open-mode=append
#SBATCH --output=/lustre/fsw/coreai_mlperf_training/users/dfridman/checkpoints/slurm_logs/slurm_%j.out
#SBATCH --partition=gb200
#SBATCH --time=00:15:00

set -evx

set +e

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

export HF_HOME=/checkpoints/hf
export NCCL_MNNVL_ENABLE=0

# MOUNTS="/lustre/fsw/coreai_mlperf_training/users/dfridman/checkpoints:/checkpoints"
# MOUNTS="$MOUNTS,/lustre/fsw/coreai_mlperf_training/users/dfridman/Megatron-Bridge/examples/conversion/hf_megatron_roundtrip_multi_gpu.py:/workspace/Megatron-Bridge/examples/conversion/hf_megatron_roundtrip_multi_gpu.py"
# MOUNTS="$MOUNTS,/lustre/share/coreai_mlperf_training/data/dsv3/mbridge-ckpt:/input_checkpoint"

MOUNTS="/lustre/fsw/coreai_mlperf_training/users/dfridman/checkpoints:/checkpoints,/lustre/fsw/coreai_mlperf_training/users/dfridman/Megatron-Bridge/examples/conversion/hf_megatron_roundtrip_multi_gpu.py:/workspace/Megatron-Bridge/examples/conversion/hf_megatron_roundtrip_multi_gpu.py,/lustre/fsw/coreai_mlperf_training/users/dfridman/Megatron-Bridge/src/megatron/bridge/models:/workspace/Megatron-Bridge/src/megatron/bridge/models,/lustre/share/coreai_mlperf_training/data/dsv3/mbridge-ckpt/iter_0000000/:/megatron_checkpoint"

srun --container-mounts $MOUNTS \
     --container-image gitlab-master.nvidia.com:5005/dl/mlperf/optimized:deepseekv3_671b.pytorch.43842447 \
     --no-container-mount-home \
     torchrun \
       --nnodes 64 \
       --nproc_per_node 4 \
       --rdzv_id $RANDOM \
       --rdzv_backend c10d \
       --rdzv_endpoint $head_node_ip:29500 \
       /workspace/Megatron-Bridge/examples/conversion/hf_megatron_roundtrip_multi_gpu.py \
       --hf-model-id deepseek-ai/DeepSeek-V3-Base \
       --tp 1 --pp 4 --vp 4 --ep 16 \
       --megatron-load-path /megatron_checkpoint \
       --trust-remote-code \
       --output-dir /checkpoints/fixed_iter
